namespace: fleet-mc-helm-example
targetCustomizations:
- name: test
  helm:
    values:
      replicas: 10
  clusterSelector:
    matchLabels:
      env: test

- name: prod
  helm:
    values:
      serviceType: LoadBalancer
      replicas: 10
  clusterSelector:
    matchLabels:
      env: prod
